import re

POLICY_SINGLE_FETCH = "single-fetch class-first (retry disabled by default)"
CLASS_FQCN_PATTERN = re.compile(r"\bAutodesk\.Revit\.([A-Za-z0-9_.]+)\b", flags=re.ASCII)
METHOD_PATTERN = re.compile(r"^(\w+)\.(\w+)$", flags=re.ASCII)
SHORT_CLASS_PATTERN = re.compile(r"^\w+$", flags=re.ASCII)
CAMEL_TOKEN_PATTERN = re.compile(r"[A-Z]?[a-z]+|[A-Z]+(?=[A-Z]|$)|\d+", flags=re.ASCII)
UI_SELECTION_NAMESPACE = "UI.Selection"

NAMESPACE_TAILS = (
    "DB",
    "Analysis",
    "Architecture",
    "Attributes",
    "Creation",
    "DirectContext3D",
    "Electrical",
    "Events",
    "Exceptions",
    "ExtensibleStorage",
    "ExternalData",
    "ExternalService",
    "Fabrication",
    "IFC",
    "Infrastructure",
    "Lighting",
    "Macros",
    "Mechanical",
    "Plumbing",
    "PointClouds",
    "Steel",
    "Structure",
    "UI",
    "UI.Events",
    "UI.Macros",
    "UI.Mechanical",
    "UI.Plumbing",
    UI_SELECTION_NAMESPACE,
    "Visual",
    "ApplicationServices",
    "CloudWorksharing",
)

DB_SUBNAMESPACES = (
    "Analysis",
    "Architecture",
    "DirectContext3D",
    "Electrical",
    "Events",
    "ExtensibleStorage",
    "ExternalData",
    "ExternalService",
    "Fabrication",
    "IFC",
    "Infrastructure",
    "Lighting",
    "Macros",
    "Mechanical",
    "Plumbing",
    "PointClouds",
    "Steel",
    "Structure",
    "Visual",
)

KNOWN_NAMESPACE_TAILS = set(NAMESPACE_TAILS) | {f"DB.{suffix}" for suffix in DB_SUBNAMESPACES}

NAMESPACE_AFFINITY_KEYWORDS = {
    "DB": {"element", "document", "parameter", "geometry", "model"},
    "Analysis": {"analysis", "energy", "gbxml"},
    "Architecture": {"room", "area", "site"},
    "Attributes": {"attribute", "transaction", "regeneration", "journal"},
    "Creation": {"new", "create", "family", "instance"},
    "DirectContext3D": {"context", "render", "primitive"},
    "Electrical": {"electrical", "circuit", "wire"},
    "Events": {"event", "handler", "trigger"},
    "Exceptions": {"exception", "invalid", "argument", "operation"},
    "ExtensibleStorage": {"storage", "schema", "entity", "field", "extensible"},
    "ExternalData": {"external", "data", "source"},
    "ExternalService": {"service", "server", "registry"},
    "Fabrication": {"fabrication", "part", "hanger"},
    "IFC": {"ifc", "export", "import"},
    "Infrastructure": {"road", "bridge", "infra"},
    "Lighting": {"lighting", "illumination", "photometric"},
    "Macros": {"macro", "script", "module"},
    "Mechanical": {"mechanical", "duct", "hvac"},
    "Plumbing": {"plumbing", "pipe", "fluid"},
    "PointClouds": {"point", "cloud", "scan"},
    "Steel": {"steel", "connection", "bolt"},
    "Structure": {"structure", "beam", "column", "rebar"},
    "UI": {"ui", "command", "dialog", "selection", "ribbon"},
    "UI.Events": {"ui", "event", "view", "documentchanged"},
    "UI.Macros": {"ui", "macro", "applicationentrypoint"},
    "UI.Mechanical": {"ui", "mechanical", "hvac"},
    "UI.Plumbing": {"ui", "plumbing", "pipe"},
    UI_SELECTION_NAMESPACE: {"selection", "pick", "reference"},
    "Visual": {"visual", "shader", "appearance"},
    "ApplicationServices": {"application", "open", "document", "services"},
    "CloudWorksharing": {"cloud", "worksharing", "modelpath"},
}

NAMESPACE_PREFIX_ALIASES = {
    "DB": "DB",
    "UI": "UI",
    "Selection": UI_SELECTION_NAMESPACE,
    "ApplicationServices": "ApplicationServices",
    "Attributes": "Attributes",
    "Creation": "Creation",
    "Exceptions": "Exceptions",
    "ExtensibleStorage": "DB.ExtensibleStorage",
}

METHOD_VERB_PREFIXES = (
    "Get",
    "Set",
    "Create",
    "Open",
    "New",
    "Pick",
    "Show",
    "Add",
    "Remove",
    "Delete",
    "Load",
    "Save",
)

AMBIGUOUS_SHORT_CLASS_NAMES = {"Application", "Document"}

GENERIC_METHOD_TOKENS = {
    "get",
    "set",
    "create",
    "open",
    "new",
    "pick",
    "show",
    "add",
    "remove",
    "delete",
    "load",
    "save",
}

# Fast keyword-driven hints to avoid unnecessary namespace misroutes.
ROOT_DB_CLASS_PREFIXES = (
    "IFC",
    "Fabrication",
)

EXACT_CLASS_NAMESPACE_HINTS = {
    "StructuralConnectionHandler": "DB.Structure",
    "SteelElementProperties": "DB.Steel",
    "ExternalServiceRegistry": "DB.ExternalService",
    "FamilyManager": "DB",
    "FamilyType": "DB",
    # Views — all live in DB, not DirectContext3D
    "View": "DB",
    "View3D": "DB",
    "ViewPlan": "DB",
    "ViewSection": "DB",
    "ViewSheet": "DB",
    "ViewDrafting": "DB",
    "ViewSchedule": "DB",
    "ViewFamilyType": "DB",
    # Core model classes commonly misrouted
    "Floor": "DB",
    "Ceiling": "DB",
    "Roof": "DB",
    "RoofBase": "DB",
    "FamilyInstance": "DB",
    "FamilySymbol": "DB",
    "Level": "DB",
    "Grid": "DB",
    "Wall": "DB",
    "WallType": "DB",
    "Material": "DB",
    "Element": "DB",
    "ElementId": "DB",
    "FilteredElementCollector": "DB",
    "Transaction": "DB",
    "TransactionGroup": "DB",
    "SubTransaction": "DB",
    "Parameter": "DB",
    "ParameterElement": "DB",
    "Category": "DB",
    "XYZ": "DB",
    "Line": "DB",
    "Arc": "DB",
    "Curve": "DB",
    "CurveLoop": "DB",
    "Solid": "DB",
    "GeometryElement": "DB",
    "GeometryObject": "DB",
    "GeometryInstance": "DB",
    "BoundingBoxXYZ": "DB",
    "Transform": "DB",
    "Reference": "DB",
    "Connector": "DB",
    "ConnectorSet": "DB",
    "Options": "DB",
    "Document": "DB",
    "Color": "DB",
    "TextNote": "DB",
    "Dimension": "DB",
    "DetailLine": "DB",
    "ModelLine": "DB",
    "ModelCurve": "DB",
    "ReferencePlane": "DB",
    "Group": "DB",
    "GroupType": "DB",
    "Assembly": "DB",
    "AssemblyInstance": "DB",
    "FilledRegion": "DB",
    "FilledRegionType": "DB",
    "OverrideGraphicSettings": "DB",
    "ElementFilter": "DB",
    "ElementParameterFilter": "DB",
    "FilterRule": "DB",
    "ParameterFilterElement": "DB",
    "BuiltInParameter": "DB",
    "BuiltInCategory": "DB",
    "StorageType": "DB",
    "TaskDialog": "UI",
    "UIDocument": "UI",
    "UIApplication": "UI",
    "Selection": UI_SELECTION_NAMESPACE,
    "PickedBox": UI_SELECTION_NAMESPACE,
    "ObjectType": UI_SELECTION_NAMESPACE,
    "ISelectionFilter": UI_SELECTION_NAMESPACE,
    "ExternalCommand": "UI",
    "ExternalApplication": "UI",
    "ExternalEvent": "UI",
    "ExternalEventHandler": "UI",
    "IExternalCommand": "UI",
    "IExternalApplication": "UI",
    "IExternalEventHandler": "UI",
    "ControlledApplication": "ApplicationServices",
}

METHOD_CONTEXT_NAMESPACE_HINTS: tuple[tuple[str, str, str], ...] = (
    ("Document", "New", "Creation"),
    ("View3D", "Create", "DB"),
    ("ViewPlan", "Create", "DB"),
    ("ViewSection", "Create", "DB"),
    ("ViewSheet", "Create", "DB"),
    ("Floor", "Create", "DB"),
    ("Ceiling", "Create", "DB"),
    ("Wall", "Create", "DB"),
    ("FamilyInstance", "New", "Creation"),
    ("Level", "Create", "DB"),
    ("Grid", "Create", "DB"),
    ("FilledRegion", "Create", "DB"),
    ("TextNote", "Create", "DB"),
    ("Dimension", "Create", "DB"),
    ("DetailLine", "Create", "DB"),
    ("ModelLine", "Create", "DB"),
    ("Arc", "Create", "DB"),
    ("Line", "Create", "DB"),
    ("Transaction", "Start", "DB"),
)
